
package proyectoempleados;
import proyectoempleados.Clases.Empleados;
import proyectoempleados.Clases.EmpleadosDao;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectoempleados.Clases.CalculadoraPlanilla;

/**
 *
 * @author franc
 */
public class planillaCalculada extends javax.swing.JFrame {
  private Set<String> empleadosProcesados = new HashSet<>();
    /**
     * Creates new form planillaCalculada
     */
    public planillaCalculada() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ausencias = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ema = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tel = new javax.swing.JLabel();
        Contrato = new javax.swing.JLabel();
        ObtNombre = new javax.swing.JLabel();
        ObtId = new javax.swing.JLabel();
        ObtDepa = new javax.swing.JLabel();
        ObtPues = new javax.swing.JLabel();
        ObtCon = new javax.swing.JLabel();
        ObtTel = new javax.swing.JLabel();
        ObtEmail = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        barraBuscar = new javax.swing.JTextField();
        BuscarId = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        extrass = new javax.swing.JTextField();
        CargarPlanilla = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Salariox = new javax.swing.JLabel();
        puesto = new javax.swing.JLabel();
        contra = new javax.swing.JLabel();
        cedu = new javax.swing.JLabel();
        Depa = new javax.swing.JLabel();
        telef = new javax.swing.JLabel();
        emai = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        sem = new javax.swing.JLabel();
        ivm = new javax.swing.JLabel();
        banco = new javax.swing.JLabel();
        capitalizacion = new javax.swing.JLabel();
        pension = new javax.swing.JLabel();
        ins = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPlanilla = new javax.swing.JTable();
        mesSelecction = new javax.swing.JComboBox<>();
        GuardarPlanilla = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ausencias.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Nombre:");

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Cedula:");

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Puesto:");

        ema.setBackground(new java.awt.Color(153, 153, 153));
        ema.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ema.setForeground(new java.awt.Color(102, 102, 102));
        ema.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Departamento:");

        tel.setBackground(new java.awt.Color(153, 153, 153));
        tel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tel.setForeground(new java.awt.Color(102, 102, 102));
        tel.setText("Telefono:");

        Contrato.setBackground(new java.awt.Color(153, 153, 153));
        Contrato.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Contrato.setForeground(new java.awt.Color(102, 102, 102));
        Contrato.setText("Contrato:");

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        barraBuscar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        barraBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                barraBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                barraBuscarFocusLost(evt);
            }
        });

        BuscarId.setForeground(new java.awt.Color(153, 153, 153));
        BuscarId.setText("Buscar");
        BuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(barraBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(BuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barraBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Horas Extra:");

        extrass.setText("0");

        CargarPlanilla.setText("Calcular Planilla");
        CargarPlanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarPlanillaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Salario Base:");

        Salariox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Salariox.setForeground(new java.awt.Color(153, 153, 153));
        Salariox.setText("jLabel5");

        puesto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        puesto.setForeground(new java.awt.Color(153, 153, 153));
        puesto.setText("jLabel5");

        contra.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        contra.setForeground(new java.awt.Color(153, 153, 153));
        contra.setText("jLabel8");

        cedu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cedu.setForeground(new java.awt.Color(153, 153, 153));
        cedu.setText("jLabel5");

        Depa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Depa.setForeground(new java.awt.Color(153, 153, 153));
        Depa.setText("jLabel5");

        telef.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        telef.setForeground(new java.awt.Color(153, 153, 153));
        telef.setText("jLabel5");

        emai.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        emai.setForeground(new java.awt.Color(153, 153, 153));
        emai.setText("jLabel8");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Aporte Patronal CCSS.");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Aporte Patronal LPT.");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("SEM, 9.25%:");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("IVM,5.08%:");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Aporte Banco,0.25%:");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Capitalizacion Laboral, 3%:");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Pensiones Complementarias,0.50%:");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("INS,1%:");

        Name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Name.setForeground(new java.awt.Color(153, 153, 153));
        Name.setText("jLabel15");

        sem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sem.setForeground(new java.awt.Color(153, 153, 153));
        sem.setText("sem");

        ivm.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ivm.setForeground(new java.awt.Color(153, 153, 153));
        ivm.setText("ivm");

        banco.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        banco.setForeground(new java.awt.Color(153, 153, 153));
        banco.setText("banco");

        capitalizacion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        capitalizacion.setForeground(new java.awt.Color(153, 153, 153));
        capitalizacion.setText("capi");

        pension.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pension.setForeground(new java.awt.Color(153, 153, 153));
        pension.setText("pen");

        ins.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ins.setForeground(new java.awt.Color(153, 153, 153));
        ins.setText("ins");

        tablaPlanilla.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tablaPlanilla.setForeground(new java.awt.Color(153, 153, 153));
        tablaPlanilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaPlanilla);
        if (tablaPlanilla.getColumnModel().getColumnCount() > 0) {
            tablaPlanilla.getColumnModel().getColumn(0).setResizable(false);
            tablaPlanilla.getColumnModel().getColumn(1).setResizable(false);
            tablaPlanilla.getColumnModel().getColumn(2).setResizable(false);
            tablaPlanilla.getColumnModel().getColumn(3).setResizable(false);
        }

        mesSelecction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Octubre", "Noviembre" }));

        GuardarPlanilla.setText("Guardar ");
        GuardarPlanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarPlanillaActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ausenciasLayout = new javax.swing.GroupLayout(ausencias);
        ausencias.setLayout(ausenciasLayout);
        ausenciasLayout.setHorizontalGroup(
            ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ausenciasLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ausenciasLayout.createSequentialGroup()
                        .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ausenciasLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(ObtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ausenciasLayout.createSequentialGroup()
                                .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ausenciasLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(ausenciasLayout.createSequentialGroup()
                                                .addComponent(ObtDepa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(118, 118, 118))
                                            .addGroup(ausenciasLayout.createSequentialGroup()
                                                .addComponent(Depa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(ausenciasLayout.createSequentialGroup()
                                        .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(ausenciasLayout.createSequentialGroup()
                                                .addComponent(cedu, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(ausenciasLayout.createSequentialGroup()
                                                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ObtId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addComponent(ObtPues, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ausenciasLayout.createSequentialGroup()
                                        .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(ausenciasLayout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(ObtCon, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(ausenciasLayout.createSequentialGroup()
                                                .addComponent(Contrato, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(contra)))
                                        .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(ausenciasLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(telef, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(ausenciasLayout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(ema, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(emai, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(ausenciasLayout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Salariox, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ausenciasLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(mesSelecction, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(251, 251, 251)))
                        .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ObtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ObtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(ausenciasLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(extrass, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ausenciasLayout.createSequentialGroup()
                        .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ausenciasLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ins, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ausenciasLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pension, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ausenciasLayout.createSequentialGroup()
                                .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ausenciasLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ivm, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ausenciasLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(13, 13, 13)
                                        .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ausenciasLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(capitalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ausenciasLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(banco, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ausenciasLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(ausenciasLayout.createSequentialGroup()
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(139, 139, 139)
                                                .addComponent(GuardarPlanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(ausenciasLayout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addComponent(CargarPlanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(ausenciasLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ausenciasLayout.setVerticalGroup(
            ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ausenciasLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ObtNombre)
                .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ausenciasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Name)))
                    .addGroup(ausenciasLayout.createSequentialGroup()
                        .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ausenciasLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ObtId)
                                    .addComponent(ObtPues)
                                    .addComponent(ObtTel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ausenciasLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(Salariox))
                                .addGap(16, 16, 16)))
                        .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cedu)
                            .addComponent(jLabel4)
                            .addComponent(puesto)
                            .addComponent(tel)
                            .addComponent(telef))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ausenciasLayout.createSequentialGroup()
                                .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ObtDepa)
                                    .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ObtCon)
                                        .addComponent(ObtEmail)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(Depa))
                                    .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Contrato)
                                        .addComponent(contra))))
                            .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ema)
                                .addComponent(emai)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(extrass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ausenciasLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(sem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ivm))
                        .addGap(48, 48, 48)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(banco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(capitalizacion)))
                    .addGroup(ausenciasLayout.createSequentialGroup()
                        .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesSelecction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(CargarPlanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(pension))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ins))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(ausenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarPlanilla)
                    .addComponent(jButton2))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ausencias, javax.swing.GroupLayout.PREFERRED_SIZE, 1004, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ausencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarIdActionPerformed
    String cedulaIngresada = barraBuscar.getText().trim();

    if (cedulaIngresada.equals("Ingrese Cedula") || cedulaIngresada.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Ingrese un número de cédula antes de cargar la planilla.", "Error", JOptionPane.ERROR_MESSAGE);
        return; 
    }

    try {
        String horasExtrasStr = extrass.getText();

       
        int horasExtras = Integer.parseInt(horasExtrasStr);

        // busca el empleado por cédula
        Empleados empleado = EmpleadosDao.consultarEmpleados("cedula", cedulaIngresada);

        
        if (empleado != null) {
            Name.setText(empleado.getNombre() + " " + empleado.getApellido());
            cedu.setText(empleado.getCedula());
            puesto.setText(empleado.getPuesto());
            Depa.setText(empleado.getDepartamento());
            contra.setText(empleado.getContrato());
            telef.setText(empleado.getTeléfono());
            emai.setText(empleado.getEmail());
            Salariox.setText(empleado.getSalario());

            CalculadoraPlanilla calculadora = new CalculadoraPlanilla(empleado);
           

        } else {
            limpiarLabels();
            JOptionPane.showMessageDialog(null, "No se encontró un empleado con la cédula proporcionada.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingrese un número entero para las horas extras y ausencias.", "Error", JOptionPane.ERROR_MESSAGE);
    }
      
    
    }//GEN-LAST:event_BuscarIdActionPerformed

    private void barraBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_barraBuscarFocusLost
        if(barraBuscar.getText().equals("")){
            barraBuscar.setText("Ingrese Cedula");
            barraBuscar.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_barraBuscarFocusLost

    private void barraBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_barraBuscarFocusGained
        if(barraBuscar.getText().equals("Ingrese Cedula")){
            barraBuscar.setText("");
            barraBuscar.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_barraBuscarFocusGained
// verifica que exitan plantillas
private boolean existePlanilla(String cedula, String mes) {
    try (BufferedReader reader = new BufferedReader(new FileReader("RegistroDePlanillas.txt"))) {
        String linea;
        while ((linea = reader.readLine()) != null) {
            String[] partes = linea.split(",");
            if (partes.length >= 6) {  // Asegúrate de que la línea tenga al menos 6 partes
                String cedulaRegistrada = partes[1].trim();
                String mesRegistrado = partes[5].trim();
                if (cedula.equals(cedulaRegistrada) && mes.equals(mesRegistrado)) {
                    return true;  // Ya existe una planilla para este empleado en el mismo mes
                }
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
    return false;  // No se encontró una planilla para este empleado en el mismo mes
}
    // permite cargar plantillas que ya esta en la base
    private void CargarPlanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarPlanillaActionPerformed
      
 try {
        Empleados empleado = EmpleadosDao.consultarEmpleados("cedula", barraBuscar.getText());
        String horasExtrasx = extrass.getText();
        int horasExtras = Integer.parseInt(horasExtrasx);
        
        
       
        String mesSeleccionado = mesSelecction.getSelectedItem().toString();

        if (existePlanilla(barraBuscar.getText(), mesSeleccionado)) {
            JOptionPane.showMessageDialog(null, "Ya se ha creado una planilla para este empleado en el mes seleccionado.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (empleado != null) {
            // Convierte el salario a tipo double
            double salario = Double.parseDouble(empleado.getSalario());

            // Calcula los valores necesarios con la CalculadoraPlanilla
            CalculadoraPlanilla calculadora = new CalculadoraPlanilla(empleado);
            double aporteBancoPopular = salario * 0.0025;
            double aporteFondoCapitalizacion = salario * 0.03;
            double aporteFondoPensiones = salario * 0.005;
            double aporteINS = salario * 0.01;
            double seguroEnfermedadMaternidad = salario * 0.0925;
            double invalidezVejezMuerte = salario * 0.0508;
            double aportePatronalCCSS = calculadora.calcularAportePatronalCCSS();
            double aportePatronalLPT = calculadora.calcularAportePatronalLPT();
            double pagoHorasExtras = calculadora.calcularHorasExtras(horasExtras);
            double rebajaPorHorasTardias = calculadora.rebajaTardias();
            double descuentoPorAusencias = calculadora.calcularDescuentoPorAusencias();
            double salarioNeto = calculadora.calcularSalarioNeto(horasExtras);
            

            // atualiza los label con los valores calculados
            banco.setText(""+aporteBancoPopular);
            capitalizacion.setText("" + aporteFondoCapitalizacion);
            pension.setText("" + aporteFondoPensiones);
            ins.setText("" + aporteINS);
            ivm.setText("" + invalidezVejezMuerte);
            sem.setText("" + seguroEnfermedadMaternidad);

            DefaultTableModel model = new DefaultTableModel(new Object[]{"Datos", "Valores"}, 0);
            model.addRow(new Object[]{"Salario Bruto", salario});
            model.addRow(new Object[]{"Aporte Patronal CCSS", "-"+aportePatronalCCSS});
            model.addRow(new Object[]{"Aporte Patronal LPT", "-"+aportePatronalLPT});
            model.addRow(new Object[]{"Pago por Horas Extras", "+"+pagoHorasExtras});
            model.addRow(new Object[]{"Rebaja Tardias", "-"+ + rebajaPorHorasTardias});
            model.addRow(new Object[]{"Rebaja por Ausencias", "-"+descuentoPorAusencias});
            model.addRow(new Object[]{"Salario Neto", salarioNeto});

           
            tablaPlanilla.setModel(model);

            JOptionPane.showMessageDialog(null, "Planilla cargada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            limpiarLabels();
            JOptionPane.showMessageDialog(null, "No se encontró un empleado con la cédula proporcionada.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingrese un número entero para las horas extras.", "Error", JOptionPane.ERROR_MESSAGE);
    }
        
        
    }//GEN-LAST:event_CargarPlanillaActionPerformed

    //nos permite guadar en el txt
    private void GuardarPlanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarPlanillaActionPerformed
     try {
        String mesSeleccionado = mesSelecction.getSelectedItem().toString();
        String clave = barraBuscar.getText() + mesSeleccionado;

        if (existePlanilla(barraBuscar.getText(), mesSeleccionado)) {
            JOptionPane.showMessageDialog(null, "Ya se ha creado una planilla para este empleado en el mes seleccionado.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
           guardarDatosEnArchivo();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un número entero para las horas extras.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_GuardarPlanillaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Menu menuu= new Menu();
        menuu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
        private void limpiarLabels() {
            Name.setText("");
            cedu.setText("");
            puesto.setText("");
            Depa.setText("");
            contra.setText("");
            telef.setText("");
            emai.setText("");
        }
       private void guardarDatosEnArchivo() {
         try (BufferedWriter escritor = new BufferedWriter(new FileWriter("RegistroDePlanillas.txt", true))) {
           
            String nombre = Name.getText();
            String cedula = cedu.getText();
            String contrato = contra.getText();
            String departamento = Depa.getText();
            String puestos = puesto.getText();
            String mesSeleccionado = mesSelecction.getSelectedItem().toString();
            String clave = cedula + mesSeleccionado;
            
            if (empleadosProcesados.contains(clave)) {
                JOptionPane.showMessageDialog(null, "Este empleado ya ha sido procesado para el mes seleccionado.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

           
            escritor.write(nombre + "," + cedula + "," + contrato + "," + departamento + "," + puestos + "," + mesSeleccionado + ",");
        
        // Agregar datos de la tabla al final de la línea
        DefaultTableModel modelo = (DefaultTableModel) tablaPlanilla.getModel();
        for (int fila = 0; fila < modelo.getRowCount(); fila++) {
            for (int columna = 0; columna < modelo.getColumnCount(); columna++) {
                escritor.write(modelo.getValueAt(fila, columna).toString() + ",");
            }
        }
        
        escritor.newLine();

        empleadosProcesados.add(clave);

        JOptionPane.showMessageDialog(null, "Datos guardados correctamente ", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Error al intentar guardar los datos en el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }       
        /**
     * @param args the command line arguments
     */
        
        
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(planillaCalculada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(planillaCalculada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(planillaCalculada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(planillaCalculada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new planillaCalculada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarId;
    private javax.swing.JButton CargarPlanilla;
    private javax.swing.JLabel Contrato;
    private javax.swing.JLabel Depa;
    private javax.swing.JButton GuardarPlanilla;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel ObtCon;
    private javax.swing.JLabel ObtDepa;
    private javax.swing.JLabel ObtEmail;
    private javax.swing.JLabel ObtId;
    private javax.swing.JLabel ObtNombre;
    private javax.swing.JLabel ObtPues;
    private javax.swing.JLabel ObtTel;
    private javax.swing.JLabel Salariox;
    private javax.swing.JPanel ausencias;
    private javax.swing.JLabel banco;
    private javax.swing.JTextField barraBuscar;
    private javax.swing.JLabel capitalizacion;
    private javax.swing.JLabel cedu;
    private javax.swing.JLabel contra;
    private javax.swing.JLabel ema;
    private javax.swing.JLabel emai;
    private javax.swing.JTextField extrass;
    private javax.swing.JLabel ins;
    private javax.swing.JLabel ivm;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> mesSelecction;
    private javax.swing.JLabel pension;
    private javax.swing.JLabel puesto;
    private javax.swing.JLabel sem;
    private javax.swing.JTable tablaPlanilla;
    private javax.swing.JLabel tel;
    private javax.swing.JLabel telef;
    // End of variables declaration//GEN-END:variables
}
